### PR TITLE
Bump to v1.0.0

### PR DESCRIPTION
**Pull request by czj**
Hooray ! (ignore the Markdown styling errors from Codacy)

### CODE REVIEW

**Comment by czj** [comment]
Ignore the Markdown styling errors from Codacy :)

**Comment by czj** [comment]
Nothing more to do to release @bobmaerten ? Beside publishing on Rubygems ?

**Comment by bobmaerten** [comment]
We have a rake task to deal with automatic changelog updates from issues and pull requests: `rake changelog` which compare specified version in `version.rb` with latest git tag.

**Comment by bobmaerten** [comment]
by the way, I did not find a way to specify the current PR to be inserted in the changelog. After merging  this one, running changelog rake task again would add this merged PR to the list.

**Pull request merged**
